# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Explore the academic journey and research endeavors of Raymond MacNeil, a dedicated PhD student in Psychology at the University of British Columbia. Discover his expertise in cognitive psychology, social psychology, and neuropsychology, with a focus on the intersection of technology and human behavior. Dive into his projects, publications, and achievements, and connect to explore collaboration opportunities.'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: false
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Raymond MacNeil. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/justindhillon/Raymond-Macneil-Portfolio'
    branch: main
